// Code generated by goctl. DO NOT EDIT.
// Source: buy.proto

package server

import (
	"context"

	"graduate_design/buy/rpc/internal/logic"
	"graduate_design/buy/rpc/internal/svc"
	"graduate_design/buy/rpc/types/buy"
)

type BuyServer struct {
	svcCtx *svc.ServiceContext
	buy.UnimplementedBuyServer
}

func NewBuyServer(svcCtx *svc.ServiceContext) *BuyServer {
	return &BuyServer{
		svcCtx: svcCtx,
	}
}

func (s *BuyServer) SetProducts(ctx context.Context, in *buy.BuyProductsRequest) (*buy.BuyProductsResponse, error) {
	l := logic.NewSetProductsLogic(ctx, s.svcCtx)
	return l.SetProducts(in)
}

func (s *BuyServer) SetOrder(ctx context.Context, in *buy.SetOrderRequest) (*buy.SetOrderResponse, error) {
	l := logic.NewSetOrderLogic(ctx, s.svcCtx)
	return l.SetOrder(in)
}
