// Code generated by goctl. DO NOT EDIT.
package types

type BuyRequest struct {
	UserId    int64 `json:"user_id"`
	ProductId int64 `json:"product_id"`
}

type BuyResponse struct {
	Status  string `json:"status"`
	Code    uint   `json:"code"`
	Message string `json:"message"`
}
