// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"graduate_design/user/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OpenAuthRequest  = user.OpenAuthRequest
	OpenAuthResponse = user.OpenAuthResponse
	UserAuthRequest  = user.UserAuthRequest
	UserAuthResponse = user.UserAuthResponse

	User interface {
		Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserAuthResponse, error)
		OpenAuth(ctx context.Context, in *OpenAuthRequest, opts ...grpc.CallOption) (*OpenAuthResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserAuthResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Auth(ctx, in, opts...)
}

func (m *defaultUser) OpenAuth(ctx context.Context, in *OpenAuthRequest, opts ...grpc.CallOption) (*OpenAuthResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.OpenAuth(ctx, in, opts...)
}
