// Code generated by goctl. DO NOT EDIT.
package types

type Device struct {
	Name           string `json:"name"`
	UserId         string `json:"userid"`
	Key            string `json:"key"`
	Secret         string `json:"secret"`
	LastOnlineTime int64  `json:"last_online_time"`
}

type ProductBasic struct {
	Name  string  `json:"name"`
	Count int     `json:"count"`
	Price float64 `json:"price"`
	Img   string  `json:"img"`
}

type Product struct {
	Name          string  `json:"name, optional"`
	Img           string  `json:"img, optional"`
	Price         float64 `json:"price, optional"`
	Origin        string  `json:"origin, optional"`
	Brand         string  `json:"brand, optional"`
	Specification string  `json:"specification, optional"`
	ShelfLife     string  `json:"shelflife, optional"`
	Description   string  `json:"description, optional"`
	Count         int     `json:"count, optional"`
	Type          string  `json:"type, optional"`
	Latitude      float64 `json:"latitude, optional"`
	Longitude     float64 `json:"longitude, optional"`
	Location      string  `json:"location, optional"`
}

type DeviceListRequest struct {
	BaseRequest
}

type DeviceListResponse struct {
	List  []*Device `json:"list"`
	Count int64     `json:"count"`
}

type  DeviceAddRequest struct {
	Name   string `json:"name, optional"`
	UserId uint `json:"userid, optional"`
}

type DeviceAddResponse struct {
	BaseResponse
}

type DeviceModifyRequest struct {
	Id uint `json:"id"`
	DeviceAddRequest
}

type DeviceModifyResponse struct {
	BaseResponse
}

type DeviceDeleteRequest struct {
	Id string `json:"id"`
}

type DeviceDeleteResponse struct {
	BaseResponse
}

type ProductListRequest struct {
	BaseRequest
}

type ProductListResponse struct {
	List  []*Product `json:"list"`
	Count int64      `json:"count"`
}

type ProductAddRequest struct {
	BaseRequest
	Data Product `json:"data"`
}

type ProductAddResponse struct {
	BaseResponse
}

type ProductModifyRequest struct {
	BaseRequest
	Data Product `json:"data"`
}

type ProductModifyResponse struct {
	BaseResponse
}

type ProductDeleteRequest struct {
	BaseRequest
}

type ProductDeleteResponse struct {
	BaseResponse
}

type BaseRequest struct {
	Page   uint   `json:"page,optional"`
	Id     uint   `json:"id, optional"`
	Size   uint   `json:",optional"`
	Name   string `json:"name, optional"`
}

type BaseResponse struct {
	Msg string `json:"msg"`
	Code uint `json:"code"`
}