Name: product-api
Host: 0.0.0.0
Port: 8040
UserRPC:
  Etcd:
    Hosts:
      - etcd:2379
    Key: user.rpc
ProductRPC:
  Etcd:
    Hosts:
      - etcd:2379
    Key: product.rpc

Prometheus:
  Host: 0.0.0.0
  Port: 9040
  Path: /metrics

Telemetry:
  Name: product.api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger