// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	Nickname string `json:"nickname"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Status  string              `json:"status"`
	Code    uint                `json:"code"`
	Message string              `json:"message"`
	Data    UserData    `json:"data"`
}

type UserData struct {
	Id 		 uint   `json:"id"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
	Motto    string `json:"motto"`
	Gender   string `json:"gender"`
	Age      uint   `json:"age"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

//管理员注册，需要添加is_admin字段，值为1
type UserRegisterRequest struct {
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
	Motto    string `json:"motto"`
	Gender   string `json:"gender"`
	Age      uint   `json:"age"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Password string `json:"password"`
	IsAdmin  uint   `json:"is_admin, optional"`
}

type UserRegisterResponse struct {
	Status  string `json:"status"`
	Code    uint   `json:"code"`
	Message string `json:"message"`
}
