// Code generated by goctl. DO NOT EDIT.
// Source: device.proto

package deviceclient

import (
	"context"

	"graduate_design/device/types/device"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendMessageRequest  = device.SendMessageRequest
	SendMessageResponse = device.SendMessageResponse

	Device interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	}

	defaultDevice struct {
		cli zrpc.Client
	}
)

func NewDevice(cli zrpc.Client) Device {
	return &defaultDevice{
		cli: cli,
	}
}

func (m *defaultDevice) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := device.NewDeviceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}
