Name: product.rpc
ListenOn: 0.0.0.0:8070
Etcd:
  Hosts:
    - etcd:2379
  Key: product.rpc

RedisCli:
  Host: redis:6379

Prometheus:
  Host: 0.0.0.0
  Port: 9070
  Path: /metrics

Telemetry:
  Name: product.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger