// Code generated by goctl. DO NOT EDIT.
package types

type SendMessageRequest struct {
	AppKey    string `json:"app_key"`
	DeviceKey string `json:"device_key"`
	Data      string `json:"data"`
	Sign      string `json:"sign"`
}

type SendMessageResponse struct {
	Code    uint   `json:"code"`
	Message string `json:"message"`
}
